### ISSUE TITLE
Fails to build with GHC 8.6.4

### ISSUE THREAD

**Issue by gvolpe** [transient-haskell/transient#78]
Hi,

I'm trying to get `transient` working but unfortunately I get this error:

```
Configuring library for transient-0.6.0.1..
Preprocessing library for transient-0.6.0.1..
Building library for transient-0.6.0.1..
[1 of 7] Compiling Transient.Internals ( src/Transient/Internals.hs, dist/build/Transient/Internals.o )

src/Transient/Internals.hs:368:10: error:
    • Could not deduce (Semigroup (TransIO a))
        arising from the superclasses of an instance declaration
      from the context: Monoid a
        bound by the instance declaration
        at src/Transient/Internals.hs:368:10-39
    • In the instance declaration for ‘Monoid (TransIO a)’
    |
368 | instance Monoid a => Monoid (TransIO a) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build transient-0.6.0.1 (which is required by
exe:effects-playground from effects-playground-0.1.0.0). See the build log
above for details.
```

Any ideas on how to solve it?

I have a few other dependencies such as `polysemy` and `fused-effects` working.

**Comment by agocorona** [comment]
Hi @gvolpe which version are you using of transient? Please use the one in github:

 https://github.com/transient-haskell/transient

**Comment by gvolpe** [comment]
I tried with the latest `0.6.0.1`, `0.5.9` and and another older version I can't remember. Always get the same error when running `cabal new-build`. Here's my `cabal` file: https://github.com/gvolpe/effects-playground/blob/master/effects-playground.cabal

If I add `transient` I get such error. Would appreciate any help.

**Comment by agocorona** [comment]
gvolpe please try the version 0.6.3 which is not in hackage. it is in github

**Comment by gvolpe** [comment]
Oh that's what you meant! I'll wait until it's published then, no rush. Thanks.
