### ISSUE TITLE
build failure: TypeRep not in scope

### ISSUE THREAD

**Issue by DanBurton** [transient-haskell/transient#70]
Build failure with GHC 8.2.1 as seen on the Stackage build server.

```
[1 of 6] Compiling Transient.Internals ( src/Transient/Internals.hs, dist/build/Transient/Internals.o )

src/Transient/Internals.hs:96:26: error:
    Not in scope: type constructor or class ‘TypeRep’
   |
96 |   , mfData      :: M.Map TypeRep SData
   |                          ^^^^^^^
```

**Comment by agocorona** [comment]
Do you know the version of  the package base used?

**Comment by DanBurton** [comment]
The one that ships with GHC 8.2.1: `base-4.10.0.0`

**Comment by agocorona** [comment]
need to import Data.Typeable.

However there are some other dependencies that still does not compile with ghc-8.2.1. IIn particular, atomic-primops, which is a new dependency. will take some time before this packages is actualized.

https://github.com/rrnewton/haskell-lockfree/issues/66

As soon as it is available I will create a new version.
